
services:
  backend:
    build: ./backend/PosApi
    container_name: pos-backend
    ports:
      - "5192:8080"

  frontend:
    build: ./frontend
    container_name: pos-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend